# Generated by Django 3.2.8 on 2021-11-22 16:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBoards',
            fields=[
                ('messageBoard_id', models.IntegerField(primary_key=True, serialize=False,
                                                        validators=[django.core.validators.MinValueValidator(0)])),
                ('courseName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('message_id', models.IntegerField(primary_key=True, serialize=False,
                                                   validators=[django.core.validators.MinValueValidator(0)])),
                ('msgDate', models.DateField()),
                ('text', models.TextField()),
                ('messageBoard',
                 models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='messages_Forum',
                                   to='AcadeMeData.messageboards')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                             to='AcadeMeData.messages')),
                ('tags', models.ManyToManyField(related_name='messages_tag', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('university_id', models.IntegerField(primary_key=True, serialize=False,
                                                      validators=[django.core.validators.MinValueValidator(0)])),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                      to='auth.user')),
                ('type', models.CharField(choices=[('S', 'Student'), ('E', 'Expert')], default='S', max_length=1)),
                ('university', models.CharField(
                    choices=[('RU', 'Reichman University'), ('HU', 'Hebrew University'), ('TA', 'Tel Aviv University'),
                             ('BS', "Be'er Sheva University"), ('UN', 'Unknown')], default='UN', max_length=2)),
                ('degree', models.CharField(
                    choices=[('CS', 'Computer Science'), ('PS', 'Psychology'), ('GV', 'GOVERNMENT'),
                             ('BA', 'Business Administration'), ('UN', 'Unknown')], default='UN', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('professor_id', models.IntegerField(primary_key=True, serialize=False,
                                                     validators=[django.core.validators.MinValueValidator(0)])),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('rate', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True,
                                             validators=[django.core.validators.MinValueValidator(1),
                                                         django.core.validators.MaxValueValidator(5)])),
                ('university',
                 models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AcadeMeData.university')),
            ],
        ),
        migrations.CreateModel(
            name='MessageTags',
            fields=[
                ('messageTags_id', models.IntegerField(primary_key=True, serialize=False,
                                                       validators=[django.core.validators.MinValueValidator(0)])),
                ('message',
                 models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='messagetags_tag',
                                   to='AcadeMeData.messages')),
                ('users',
                 models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='messagetags_author',
                                   to='AcadeMeData.users')),
            ],
        ),
        migrations.AddField(
            model_name='messages',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='messages_author',
                                    to='AcadeMeData.users'),
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('Degree_id', models.IntegerField(primary_key=True, serialize=False,
                                                  validators=[django.core.validators.MinValueValidator(0)])),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('university',
                 models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AcadeMeData.university')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False,
                                                  validators=[django.core.validators.MinValueValidator(0)])),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('rate', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True,
                                             validators=[django.core.validators.MinValueValidator(1),
                                                         django.core.validators.MaxValueValidator(5)])),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AcadeMeData.degree')),
                ('professor',
                 models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AcadeMeData.professor')),
            ],
        ),
    ]
