# Generated by Django 3.2.9 on 2021-11-27 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AcadeMeData', '0002_User_test_data'),
        ('AcadeMeData', '0003_messageBoards_test_data'),
        ('AcadeMeData', '0004_messages_test_data'),
        ('AcadeMeData', '0006_university_test_data'),
        ('AcadeMeData', '0008_Professor_test_data'),
    ]

    operations = [
    ]
