# Generated by Django 3.2.9 on 2021-12-25 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AcadeMeData', '0003_messageBoards_test_data'),
        ('AcadeMeData', '0004_messages_test_data'),
        ('AcadeMeData', '0005_messageTags_test_data'),
        ('AcadeMeData', '0007_Degree_test_data'),
        ('AcadeMeData', '0008_Professor_test_data'),
        ('AcadeMeData', '0009_Course_test_data'),
    ]

    operations = [
    ]
