# Generated by Django 3.2.9 on 2021-11-27 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcadeMeData', '0009_merge_20211127_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='professor_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
