# Generated by Django 3.2.9 on 2021-12-29 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AcadeMeData', '0007_Degree_test_data'),
        ('AcadeMeData', '0008_Professor_test_data'),
        ('AcadeMeData', '0009_Course_test_data'),
    ]

    operations = [
    ]
