# Generated by Django 3.2.9 on 2021-11-27 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcadeMeData', '0010_alter_professor_professor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='university_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
