# Generated by Django 3.2.9 on 2021-12-29 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AcadeMeData', '0005_messageTags_test_data'),
        ('AcadeMeData', '0011_auto_20211229_1454'),
    ]

    operations = [
    ]
