# Generated by Django 3.2.9 on 2021-12-29 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AcadeMeData', '0011_alter_messages_board'),
        ('AcadeMeData', '0012_merge_20211229_1454'),
    ]

    operations = [
    ]
