# Generated by Django 3.2.9 on 2021-11-30 22:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('studies', '0002_university_test_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('professor_id', models.IntegerField(primary_key=True, serialize=False,
                                                     validators=[django.core.validators.MinValueValidator(0)])),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True,
                                             validators=[django.core.validators.MinValueValidator(1),
                                                         django.core.validators.MaxValueValidator(5)])),
                (
                    'university',
                    models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='studies.university')),
            ],
        ),
    ]
